@@@@@@@@@@
// nfoenbiovbeiobvoieb
Program ArrayExample; {bbrebere}

Var var1 : Integer; {Comment
....
..}
Var var2 : Real;
Var var3 : Boolean;
Var var3 : Boolean;

function MYFUNC (var1,y : integer) : boolean;

Begin
    if (var3 AND var3) then
        var2 := 42.1
End;

function MYFUNC (x : integer) : boolean;

Begin
    if x then
        var2 := 42
End;

function MYFUNC (x,y : integer) : boolean;

Begin
    if (x > y) then
        var2 := 42.6
End;

Begin
    myVar := 999
End