
Program ArrayExample; {bbrebere}
var arr1 : array [ 1 .. 9 ] of Integer;
Var var1 : Integer;

{
function MYFUNC (arr2 : array [ 1 .. 9 ] of Integer) : boolean;

Begin
    //var1 := 100;

    arr2[0] := 2
    //arr2 := 3
End;
}

procedure MYPROD (var1,y : integer);

Var localVar : Integer;

Begin
    var2 := 1.1;
    localVar := 100;
    if (true AND true) then
        var2 := 42.1
End;


Begin

 MYPROD(1,1)

 //arr1 := 5;

 //arr1[0] := 5;

 //var1 := 5
    
End